# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\nonas\Documents\python_projects\Calculator\cal_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(321, 375)
        Form.setMinimumSize(QtCore.QSize(321, 375))
        Form.setMaximumSize(QtCore.QSize(321, 375))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("\n"
"QWidget#Form{\n"
"background-color:#4d4d4d;\n"
"}\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.multiplication = QtWidgets.QPushButton(Form)
        self.multiplication.setMinimumSize(QtCore.QSize(65, 65))
        self.multiplication.setMaximumSize(QtCore.QSize(65, 65))
        self.multiplication.setStyleSheet("QPushButton{\n"
"background-color: #65c8cf;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.multiplication.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/signs/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.multiplication.setIcon(icon1)
        self.multiplication.setIconSize(QtCore.QSize(40, 40))
        self.multiplication.setAutoDefault(False)
        self.multiplication.setDefault(False)
        self.multiplication.setFlat(True)
        self.multiplication.setObjectName("multiplication")
        self.gridLayout.addWidget(self.multiplication, 2, 3, 1, 1)
        self.one = QtWidgets.QPushButton(Form)
        self.one.setMinimumSize(QtCore.QSize(65, 65))
        self.one.setMaximumSize(QtCore.QSize(65, 65))
        self.one.setStyleSheet("QPushButton{\n"
"background-color: #808080;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.one.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/numbers/icons/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.one.setIcon(icon2)
        self.one.setIconSize(QtCore.QSize(55, 55))
        self.one.setAutoDefault(False)
        self.one.setDefault(False)
        self.one.setFlat(True)
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 3, 0, 1, 1)
        self.nine = QtWidgets.QPushButton(Form)
        self.nine.setMinimumSize(QtCore.QSize(65, 65))
        self.nine.setMaximumSize(QtCore.QSize(65, 65))
        self.nine.setStyleSheet("QPushButton{\n"
"background-color: #808080;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.nine.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/numbers/icons/9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nine.setIcon(icon3)
        self.nine.setIconSize(QtCore.QSize(55, 55))
        self.nine.setAutoDefault(False)
        self.nine.setDefault(False)
        self.nine.setFlat(True)
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 1, 2, 1, 1)
        self.seven = QtWidgets.QPushButton(Form)
        self.seven.setMinimumSize(QtCore.QSize(65, 65))
        self.seven.setMaximumSize(QtCore.QSize(65, 65))
        self.seven.setStyleSheet("QPushButton{\n"
"background-color: #808080;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.seven.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/numbers/icons/7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.seven.setIcon(icon4)
        self.seven.setIconSize(QtCore.QSize(55, 55))
        self.seven.setAutoDefault(False)
        self.seven.setDefault(False)
        self.seven.setFlat(False)
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 1, 0, 1, 1)
        self.four = QtWidgets.QPushButton(Form)
        self.four.setMinimumSize(QtCore.QSize(65, 65))
        self.four.setMaximumSize(QtCore.QSize(65, 65))
        self.four.setStyleSheet("QPushButton{\n"
"background-color: #808080;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.four.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/numbers/icons/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.four.setIcon(icon5)
        self.four.setIconSize(QtCore.QSize(55, 55))
        self.four.setAutoDefault(False)
        self.four.setDefault(False)
        self.four.setFlat(True)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 2, 0, 1, 1)
        self.five = QtWidgets.QPushButton(Form)
        self.five.setMinimumSize(QtCore.QSize(65, 65))
        self.five.setMaximumSize(QtCore.QSize(65, 65))
        self.five.setStyleSheet("QPushButton{\n"
"background-color: #808080;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.five.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/numbers/icons/5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.five.setIcon(icon6)
        self.five.setIconSize(QtCore.QSize(55, 55))
        self.five.setAutoDefault(False)
        self.five.setDefault(False)
        self.five.setFlat(True)
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 2, 1, 1, 1)
        self.eight = QtWidgets.QPushButton(Form)
        self.eight.setMinimumSize(QtCore.QSize(65, 65))
        self.eight.setMaximumSize(QtCore.QSize(65, 65))
        self.eight.setStyleSheet("QPushButton{\n"
"background-color: #808080;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.eight.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/numbers/icons/8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eight.setIcon(icon7)
        self.eight.setIconSize(QtCore.QSize(55, 55))
        self.eight.setAutoDefault(False)
        self.eight.setDefault(False)
        self.eight.setFlat(True)
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 1, 1, 1, 1)
        self.six = QtWidgets.QPushButton(Form)
        self.six.setMinimumSize(QtCore.QSize(65, 65))
        self.six.setMaximumSize(QtCore.QSize(65, 65))
        self.six.setStyleSheet("QPushButton{\n"
"background-color: #808080;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.six.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/numbers/icons/6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.six.setIcon(icon8)
        self.six.setIconSize(QtCore.QSize(55, 55))
        self.six.setAutoDefault(False)
        self.six.setDefault(False)
        self.six.setFlat(True)
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 2, 2, 1, 1)
        self.input = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.input.setFont(font)
        self.input.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.input.setStyleSheet("background-color: #d1e5a8;\n"
"border: 3px solid gray;\n"
"border-radius: 5px;")
        self.input.setText("")
        self.input.setReadOnly(True)
        self.input.setObjectName("input")
        self.gridLayout.addWidget(self.input, 0, 0, 1, 4)
        self.division = QtWidgets.QPushButton(Form)
        self.division.setMinimumSize(QtCore.QSize(65, 65))
        self.division.setMaximumSize(QtCore.QSize(65, 65))
        self.division.setStyleSheet("QPushButton{\n"
"background-color: #65c8cf;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.division.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/signs/icons/division.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.division.setIcon(icon9)
        self.division.setIconSize(QtCore.QSize(40, 40))
        self.division.setAutoDefault(False)
        self.division.setDefault(False)
        self.division.setFlat(True)
        self.division.setObjectName("division")
        self.gridLayout.addWidget(self.division, 1, 3, 1, 1)
        self.minus = QtWidgets.QPushButton(Form)
        self.minus.setMinimumSize(QtCore.QSize(65, 65))
        self.minus.setMaximumSize(QtCore.QSize(65, 65))
        self.minus.setStyleSheet("QPushButton{\n"
"background-color: #65c8cf;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.minus.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/signs/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minus.setIcon(icon10)
        self.minus.setIconSize(QtCore.QSize(40, 40))
        self.minus.setAutoDefault(False)
        self.minus.setDefault(False)
        self.minus.setFlat(True)
        self.minus.setObjectName("minus")
        self.gridLayout.addWidget(self.minus, 3, 3, 1, 1)
        self.point = QtWidgets.QPushButton(Form)
        self.point.setMinimumSize(QtCore.QSize(65, 65))
        self.point.setMaximumSize(QtCore.QSize(65, 65))
        self.point.setStyleSheet("QPushButton{\n"
"background-color: #808080;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.point.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/numbers/icons/point.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.point.setIcon(icon11)
        self.point.setIconSize(QtCore.QSize(55, 55))
        self.point.setAutoDefault(False)
        self.point.setDefault(False)
        self.point.setFlat(True)
        self.point.setObjectName("point")
        self.gridLayout.addWidget(self.point, 4, 1, 1, 1)
        self.equals = QtWidgets.QPushButton(Form)
        self.equals.setMinimumSize(QtCore.QSize(65, 65))
        self.equals.setMaximumSize(QtCore.QSize(65, 65))
        self.equals.setStyleSheet("QPushButton{\n"
"background-color: #e75c5e;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.equals.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/signs/icons/equal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.equals.setIcon(icon12)
        self.equals.setIconSize(QtCore.QSize(40, 40))
        self.equals.setAutoDefault(False)
        self.equals.setDefault(False)
        self.equals.setFlat(True)
        self.equals.setObjectName("equals")
        self.gridLayout.addWidget(self.equals, 4, 2, 1, 1)
        self.three = QtWidgets.QPushButton(Form)
        self.three.setMinimumSize(QtCore.QSize(65, 65))
        self.three.setMaximumSize(QtCore.QSize(65, 65))
        self.three.setStyleSheet("QPushButton{\n"
"background-color: #808080;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.three.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/numbers/icons/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.three.setIcon(icon13)
        self.three.setIconSize(QtCore.QSize(55, 55))
        self.three.setAutoDefault(False)
        self.three.setDefault(False)
        self.three.setFlat(True)
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 3, 2, 1, 1)
        self.two = QtWidgets.QPushButton(Form)
        self.two.setMinimumSize(QtCore.QSize(65, 65))
        self.two.setMaximumSize(QtCore.QSize(65, 65))
        self.two.setStyleSheet("QPushButton{\n"
"background-color: #808080;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.two.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/numbers/icons/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.two.setIcon(icon14)
        self.two.setIconSize(QtCore.QSize(55, 55))
        self.two.setAutoDefault(False)
        self.two.setDefault(False)
        self.two.setFlat(True)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 3, 1, 1, 1)
        self.zero = QtWidgets.QPushButton(Form)
        self.zero.setMinimumSize(QtCore.QSize(65, 65))
        self.zero.setMaximumSize(QtCore.QSize(65, 65))
        self.zero.setStyleSheet("QPushButton{\n"
"background-color: #808080;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.zero.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/numbers/icons/0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zero.setIcon(icon15)
        self.zero.setIconSize(QtCore.QSize(55, 55))
        self.zero.setAutoDefault(False)
        self.zero.setDefault(False)
        self.zero.setFlat(True)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 4, 0, 1, 1)
        self.plus = QtWidgets.QPushButton(Form)
        self.plus.setMinimumSize(QtCore.QSize(65, 65))
        self.plus.setMaximumSize(QtCore.QSize(65, 65))
        self.plus.setStyleSheet("QPushButton{\n"
"background-color: #65c8cf;\n"
"border-radius: 6px;}\n"
"\n"
"QPushButton:pressed {\n"
"   background-color: #e8eaea;\n"
"    border-radius: 6px;\n"
"}")
        self.plus.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/signs/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plus.setIcon(icon16)
        self.plus.setIconSize(QtCore.QSize(40, 40))
        self.plus.setAutoDefault(False)
        self.plus.setDefault(False)
        self.plus.setFlat(True)
        self.plus.setObjectName("plus")
        self.gridLayout.addWidget(self.plus, 4, 3, 1, 1)
        self.input.raise_()
        self.eight.raise_()
        self.nine.raise_()
        self.division.raise_()
        self.five.raise_()
        self.four.raise_()
        self.multiplication.raise_()
        self.six.raise_()
        self.two.raise_()
        self.one.raise_()
        self.minus.raise_()
        self.three.raise_()
        self.point.raise_()
        self.zero.raise_()
        self.plus.raise_()
        self.equals.raise_()
        self.seven.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import resources_rc
